商品購入機能の実装
FukayaHiroki/freemarket_sample_54b pull request #37
Opened 2019-07-17 09:46 UTC by tech54tu

# What
Pay.jpを導入し、クレジットカードの登録・削除機能を実装する。また、商品購入機能を実装する。

# Why
フリマアプリに必須の機能のため。

2019-07-17 10:01 UTC, harukahorii commented
ありがとうございます。
LGTMです！

2019-07-17 12:22 UTC, i-date reviewed
ご提出ありがとうございます！コメントいたしました^^
また、コンフリクトも解消しましょう。

2019-07-17 12:22 UTC, i-date commented on app/assets/stylesheets/cards.scss
> +// Place all the styles related to the cards controller here.
こちらのファイルは不要でしたら削除しましょう。

2019-07-17 12:22 UTC, i-date commented on app/controllers/products_controller.rb
> +    Payjp::Charge.create(
エラーハンドリング（例外処理）をしてみてはいかがでしょうか？

2019-07-17 12:22 UTC, i-date commented on app/controllers/products_controller.rb
> +    :currency => 'jpy'
26-28行目はハッシュロケットをシンボル型に修正しましょう。

2019-07-17 12:22 UTC, i-date commented on app/controllers/products_controller.rb
> +    redirect_to "/products/#{@product.id}/buy/done"
30行目はprefixを使用できないでしょうか？

2019-07-17 12:22 UTC, i-date commented on app/views/layouts/application.html.haml
> +    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
4行目`"http-equiv"`の後ろのハッシュロケットもシンボル型に修正しましょう。

2019-07-17 12:59 UTC, tech54tu commented
i-dateさん、ご丁寧なレビューありがとうございます！
・不要なファイルの削除
・エラーハンドリングの追加
・ハッシュロケットの修正
・コンフリクトの解消
完了いたしました。

prefixの使用ですが、product_pathを使用するとshowアクションが動いてしまうため、URLでの指定のままにしております。この旨、コメントアウトで記述するようにいたしました。
お手数をおかけいたしますが、ご確認のほどよろしくお願い致します。

2019-07-17 19:55 UTC, TOMARUMARU commented
> prefixの使用ですが、product_pathを使用するとshowアクションが動いてしまうため

それぞれにpathが指定されているはずです！
rake routesでご確認ください

2019-07-18 03:35 UTC, tech54tu commented
TOMARUMARUさん、レビューありがとうございます！
productsのルーティングにmember doの記載を追加することで、指定のpathが確認できましたので修正いたしました。

2019-07-18 03:55 UTC, TOMARUMARU requested changes
LGTM

2019-07-18 10:41 UTC, merged